name: Django CI

on:
  [push, pull_request]

jobs:
  flake8-lint:
    name: Flake8 Linting
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10.11'

      - name: Install flake8
        run: |
          python -m pip install --upgrade pip
          pip install flake8

      - name: Run flake8
        run: |
          flake8 . --max-line-length=100

  unit-tests:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis:7
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    defaults:
      run:
        working-directory: CeleryProject

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10.11'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Wait for Redis
        run: |
          for i in {1..10}; do
            nc -z localhost 6379 && echo "Redis is up" && break
            echo "Waiting for Redis..."
            sleep 3
          done

      - name: Run Tests
        env:
          CELERY_BROKER_URL: redis://localhost:6379/0
          CELERY_RESULT_BACKEND: redis://localhost:6379/0
          SECRET_KEY: django-insecure-9nl=j@28d^p=o#pa=6hb#2ks!6)q0zavf_1)gdp7!oa3gw-306
          DEBUG: 'True'
          DJANGO_ALLOWED_HOSTS: localhost,127.0.0.1,[::1]
          TZ: Asia/Karachi
          EMAIL_BACKEND: django.core.mail.backends.smtp.EmailBackend
          EMAIL_HOST: smtp.gmail.com
          EMAIL_PORT: '587'
          EMAIL_USE_TLS: 'True'
          EMAIL_HOST_USER: ashfaq319535@gmail.com
          EMAIL_HOST_PASSWORD: kroc_bszl_kkkc_qfzt
          DEFAULT_FROM_EMAIL: ashfaq319535@gmail.com
        run: |
          python manage.py test
